### ISSUE TITLE
Need help to set up Github Actions

### ISSUE THREAD

**Issue by JohannesLorenz** [calf-studio-gear/calf#335]
Hello all,

@boomshop was kind enough to grant me writing permission, so I can at least merge some of the bug fixes to maintain CALF.

Before doing that, I want to setup a Github Actions CI, to avoid introducing new errors. I got linux-gcc, linux-clang, macos and mingw64 (cross-compile) running (see branch `github-actions`), but there are still open questions:

1. Does anyone have instructions/Makefiles for MSVC compiling? I only know LMMS can do it, but they do it via CMake, which we do not use here.
2. Are there any tests? I only found bigbull/test.py, but I have no idea what it is used for.

Thanks for any help!

**Comment by erickisos** [comment]
Hey @JohannesLorenz !

I can help with the macos packaging if you want, but it will depend on the build action, wdyt?

**Comment by JohannesLorenz** [comment]
@erickisos Thanks a lot :+1: I will need to see how far I get with MacOS. For now, it looks OK. I will let you know when there are difficulties.

**Comment by JohannesLorenz** [comment]
@erickisos We currently have issue with the MacOS CI: https://github.com/calf-studio-gear/calf/actions/runs/7863604912/job/21454397740 . The exact error from this log is:

```
ld: library not found for -lgtk-quartz-2.0
```

Are you currently able to compile CALF from branch `github-actions`? Can you tell if any of the things that we do in the CI is wrong? Currently, we have this for macos-13:

```
      - name: Install dependencies
        run: brew install automake fluid-synth gtk+ cairo lv2
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=../install
      - name: Build
        run: cmake --build build
``` 

Thanks on advance.

**Comment by erickisos** [comment]
Hey @JohannesLorenz ! Let me take a quick look

**Comment by erickisos** [comment]
Hey @JohannesLorenz after debugging the build process it looks like we were missing the reference to gtk-quartz, perhaps to everything being installed by homebrew, I've created the following PR (#345) that should fix the build issue.

Let me know if it works for you!

**Comment by JohannesLorenz** [comment]
I could need your input: Can you please tell me what files I need to create to make a "release"?

@erickisos (MacOS) , @Rossmaxx (Windows)

Thanks!

**Comment by Rossmaxx** [comment]
I believe it's just some CMake stuff. If not, you'll have to look at NSIS scripts, which is beyond my knowledge. @domclark is the only one i can recommend

**Comment by erickisos** [comment]
What do you mean about "which files are needed"?
For macOS, the basic package format is just `*.pkg` but I think [this wonderful CPack thing](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Packaging%20With%20CPack.html) might be able to help us here.

**Comment by JohannesLorenz** [comment]
> What do you mean about "which files are needed"? For macOS, the basic package format is just `*.pkg`

According to [this list](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Packaging%20With%20CPack.html#options-added-by-cpack) , there are 4 generators PACKAGEMAKER, DRAGNDROP, BUNDLE and OSXX11. `PACKAGEMANAGER` sounds like "pkg", I can give that a try.

**Comment by JohannesLorenz** [comment]
@erickisos I added `cpack -G productbuild`, [but it did not work](https://github.com/calf-studio-gear/calf/actions/runs/10586275455/job/29334676762). It complained a lot about missing directories, which I do not understand. Here is what I did:

```yml
  macos:
    name: macos
    runs-on: macos-13
    steps:
      - name: Install python3
        run: brew install --overwrite python@3.12
      - name: Install dependencies
        run: brew install automake fluid-synth gtk+ lv2 gtk-mac-integration expat
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure
        run: |
          export LDFLAGS="-L$(brew --prefix)/lib"
          export CPPFLAGS="-I$(brew --prefix expat)/include"
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_SHARED_LINKER_FLAGS="-L$(brew --prefix)/lib -Wl,-rpath,$(brew --prefix)/lib" -DCMAKE_CXX_FLAGS="-I$(brew --prefix)/include"
      - name: Build
        run: cmake --build build
      - name: Package
        run: |
          cd build
          cpack -G productbuild
```
Error:
```
Error creating directory "/Users/runner/work/calf/calf/install/lib/lv2/calf.lv2".
```
Can you run these steps on your own MacBook and reproduce the error? Any idea what's wrong?
